function(doc) {
    
    var time_zone_list = [
        'Africa/Abidjan',
        'Africa/Accra',
        'Africa/Addis_Ababa',
        'Africa/Algiers',
        'Africa/Asmera',
        'Africa/Bangui',
        'Africa/Bissau',
        'Africa/Blantyre',
        'Africa/Bujumbura',
        'Africa/Cairo',
        'Africa/Casablanca',
        'Africa/Conakry',
        'Africa/Dakar',
        'Africa/Dar_es_Salaam',
        'Africa/Djibouti',
        'Africa/Douala',
        'Africa/Freetown',
        'Africa/Gaborone',
        'Africa/Harare',
        'Africa/Johannesburg',
        'Africa/Kampala',
        'Africa/Khartoum',
        'Africa/Kigali',
        'Africa/Kinshasa',
        'Africa/Lagos',
        'Africa/Libreville',
        'Africa/Lome',
        'Africa/Luanda',
        'Africa/Lubumbashi',
        'Africa/Lusaka',
        'Africa/Malabo',
        'Africa/Maputo',
        'Africa/Maseru',
        'Africa/Mbabane',
        'Africa/Mogadishu',
        'Africa/Monrovia',
        'Africa/Nairobi',
        'Africa/Ndjamena',
        'Africa/Niamey',
        'Africa/Nouakchott',
        'Africa/Ouagadougou',
        'Africa/Porto-Novo',
        'Africa/Sao_Tome',
        'Africa/Timbuktu',
        'Africa/Tripoli',
        'Africa/Tunis',
        'Africa/Windhoek',
        'America/Adak',
        'America/Anchorage',
        'America/Anguilla',
        'America/Antigua',
        'America/Aruba',
        'America/Asuncion',
        'America/Barbados',
        'America/Belize',
        'America/Bogota',
        'America/Buenos_Aires',
        'America/Caracas',
        'America/Cayenne',
        'America/Cayman',
        'America/Chicago',
        'America/Costa_Rica',
        'America/Cuiaba',
        'America/Curacao',
        'America/Dawson_Creek',
        'America/Denver',
        'America/Dominica',
        'America/Edmonton',
        'America/El_Salvador',
        'America/Fortaleza',
        'America/Godthab',
        'America/Grand_Turk',
        'America/Grenada',
        'America/Guadeloupe',
        'America/Guatemala',
        'America/Guayaquil',
        'America/Guyana',
        'America/Halifax',
        'America/Havana',
        'America/Indianapolis',
        'America/Jamaica',
        'America/La_Paz',
        'America/Lima',
        'America/Los_Angeles',
        'America/Managua',
        'America/Manaus',
        'America/Martinique',
        'America/Mazatlan',
        'America/Mexico_City',
        'America/Miquelon',
        'America/Montevideo',
        'America/Montreal',
        'America/Montserrat',
        'America/Nassau',
        'America/New_York',
        'America/Noronha',
        'America/Panama',
        'America/Paramaribo',
        'America/Phoenix',
        'America/Port-au-Prince',
        'America/Port_of_Spain',
        'America/Porto_Acre',
        'America/Puerto_Rico',
        'America/Regina',
        'America/Santiago',
        'America/Santo_Domingo',
        'America/Sao_Paulo',
        'America/Scoresbysund',
        'America/St_Johns',
        'America/St_Kitts',
        'America/St_Lucia',
        'America/St_Thomas',
        'America/St_Vincent',
        'America/Tegucigalpa',
        'America/Thule',
        'America/Tijuana',
        'America/Tortola',
        'America/Vancouver',
        'America/Winnipeg',
        'Antarctica/Casey',
        'Antarctica/DumontDUrville',
        'Antarctica/Mawson',
        'Antarctica/McMurdo',
        'Antarctica/Palmer',
        'Asia/Aden',
        'Asia/Almaty',
        'Asia/Amman',
        'Asia/Anadyr',
        'Asia/Aqtau',
        'Asia/Aqtobe',
        'Asia/Ashkhabad',
        'Asia/Baghdad',
        'Asia/Bahrain',
        'Asia/Baku',
        'Asia/Bangkok',
        'Asia/Beirut',
        'Asia/Bishkek',
        'Asia/Brunei',
        'Asia/Calcutta',
        'Asia/Colombo',
        'Asia/Dacca',
        'Asia/Damascus',
        'Asia/Dubai',
        'Asia/Dushanbe',
        'Asia/Hong_Kong',
        'Asia/Irkutsk',
        'Asia/Jakarta',
        'Asia/Jayapura',
        'Asia/Jerusalem',
        'Asia/Kabul',
        'Asia/Kamchatka',
        'Asia/Karachi',
        'Asia/Katmandu',
        'Asia/Krasnoyarsk',
        'Asia/Kuala_Lumpur',
        'Asia/Kuwait',
        'Asia/Macao',
        'Asia/Magadan',
        'Asia/Manila',
        'Asia/Muscat',
        'Asia/Nicosia',
        'Asia/Novosibirsk',
        'Asia/Phnom_Penh',
        'Asia/Pyongyang',
        'Asia/Qatar',
        'Asia/Rangoon',
        'Asia/Riyadh',
        'Asia/Saigon',
        'Asia/Seoul',
        'Asia/Shanghai',
        'Asia/Singapore',
        'Asia/Taipei',
        'Asia/Tashkent',
        'Asia/Tbilisi',
        'Asia/Tehran',
        'Asia/Thimbu',
        'Asia/Tokyo',
        'Asia/Ujung_Pandang',
        'Asia/Ulan_Bator',
        'Asia/Vientiane',
        'Asia/Vladivostok',
        'Asia/Yakutsk',
        'Asia/Yekaterinburg',
        'Asia/Yerevan',
        'Atlantic/Azores',
        'Atlantic/Bermuda',
        'Atlantic/Canary',
        'Atlantic/Cape_Verde',
        'Atlantic/Faeroe',
        'Atlantic/Jan_Mayen',
        'Atlantic/Reykjavik',
        'Atlantic/South_Georgia',
        'Atlantic/St_Helena',
        'Atlantic/Stanley',
        'Australia/Adelaide',
        'Australia/Brisbane',
        'Australia/Broken_Hill',
        'Australia/Darwin',
        'Australia/Hobart',
        'Australia/Lord_Howe',
        'Australia/Perth',
        'Australia/Sydney',
        'Europe/Amsterdam',
        'Europe/Andorra',
        'Europe/Athens',
        'Europe/Belgrade',
        'Europe/Berlin',
        'Europe/Brussels',
        'Europe/Bucharest',
        'Europe/Budapest',
        'Europe/Chisinau',
        'Europe/Copenhagen',
        'Europe/Dublin',
        'Europe/Gibraltar',
        'Europe/Helsinki',
        'Europe/Istanbul',
        'Europe/Kaliningrad',
        'Europe/Kiev',
        'Europe/Lisbon',
        'Europe/London',
        'Europe/Luxembourg',
        'Europe/Madrid',
        'Europe/Malta',
        'Europe/Minsk',
        'Europe/Monaco',
        'Europe/Moscow',
        'Europe/Oslo',
        'Europe/Paris',
        'Europe/Prague',
        'Europe/Riga',
        'Europe/Rome',
        'Europe/Samara',
        'Europe/Simferopol',
        'Europe/Sofia',
        'Europe/Stockholm',
        'Europe/Tallinn',
        'Europe/Tirane',
        'Europe/Vaduz',
        'Europe/Vienna',
        'Europe/Vilnius',
        'Europe/Warsaw',
        'Europe/Zurich',
        'Indian/Antananarivo',
        'Indian/Chagos',
        'Indian/Christmas',
        'Indian/Cocos',
        'Indian/Comoro',
        'Indian/Kerguelen',
        'Indian/Mahe',
        'Indian/Maldives',
        'Indian/Mauritius',
        'Indian/Mayotte',
        'Indian/Reunion',
        'Pacific/Apia',
        'Pacific/Auckland',
        'Pacific/Chatham',
        'Pacific/Easter',
        'Pacific/Efate',
        'Pacific/Enderbury',
        'Pacific/Fakaofo',
        'Pacific/Fiji',
        'Pacific/Funafuti',
        'Pacific/Galapagos',
        'Pacific/Gambier',
        'Pacific/Guadalcanal',
        'Pacific/Guam',
        'Pacific/Honolulu',
        'Pacific/Kiritimati',
        'Pacific/Kosrae',
        'Pacific/Majuro',
        'Pacific/Marquesas',
        'Pacific/Nauru',
        'Pacific/Niue',
        'Pacific/Norfolk',
        'Pacific/Noumea',
        'Pacific/Pago_Pago',
        'Pacific/Palau',
        'Pacific/Pitcairn',
        'Pacific/Ponape',
        'Pacific/Port_Moresby',
        'Pacific/Rarotonga',
        'Pacific/Saipan',
        'Pacific/Tahiti',
        'Pacific/Tarawa',
        'Pacific/Tongatapu',
        'Pacific/Truk',
        'Pacific/Wake',
        'Pacific/Wallis',
        'Asia/Abu Dhabi',
        'America/Alaska',
        'America/Arizona',
        'America/Atlantic Time (Canada)',
        'Asia/Beijing',
        'Asia/Canberra',
        'Europe/Bern',
        'America/Brasilia',
        'Europe/Bratislava',
        'America/Buenos Aires',
        'America/Central America',
        'America/Central Time (US &amp; Canada)',
        'Asia/Chennai',
        'America/Chihuahua',
        'Asia/Chongqing',
        'Asia/Dhaka',
        'America/Eastern Time (US &amp; Canada)',
        'Europe/Edinburgh',
        'Asia/Ekaterinburg',
        'America/Georgetown',
        'Europe/Greenland',
        'America/Guadalajara',
        'Asia/Hanoi',
        'America/Hawaii',
        'Asia/Hong Kong',
        'America/Indiana (East)',
        'America/International Date Line West',
        'Asia/Islamabad',
        'Asia/Kathmandu',
        'Asia/Kolkata',
        'Asia/Kuala Lumpur',
        'Asia/Kyiv',
        'America/La Paz',
        'Europe/Ljubljana',
        'Asia/Melbourne',
        'America/Mexico City',
        'America/Mid-Atlantic',
        'Asia/Midway Island',
        'America/Monterrey',
        'America/Mountain Time (US &amp; Canada)',
        'Asia/Mumbai',
        'Asia/New Caledonia',
        'Asia/New Delhi',
        'America/Newfoundland',
        'Asia/Nuku\'alofa',
        'Asia/Osaka',
        'America/Pacific Time (US &amp; Canada)',
        'Africa/Pretoria',
        'America/Quito',
        'Asia/Sapporo',
        'Europe/Sarajevo',
        'America/Saskatchewan',
        'Europe/Skopje',
        'Asia/Sri Jayawardenepura',
        'Asia/St. Petersburg',
        'Asia/Wellington',
        'Africa/West Central Africa',
        'Europe/Zagreb'
    ].map(function(entry) {
        return entry.split('/');
    });
    
    // create lookups
    var cities = {};
    var continents = {};
    
    time_zone_list.forEach(function(entry) {
        var continent = entry[0];
        var city = entry[1];
        if (!(city in cities)) {
            cities[city] = [];
        }
        cities[city] = continent;
        
        if (!(continent in continents)) {
            continents[continent] = [];
        }
        continents[continent].push(city);
    });
    
    if (doc.user) {
        var city = doc.user.time_zone;
        if (city != '') {
            var continent = cities[city];
            if(continent) {
                if(continent=='Africa') {
                    emit([city, continent], 1);
                }
            } else {
                emit([city, 'Unknown'], 1);
            }
        }
    }
}